// This file was auto-generated by ML.NET Model Builder. 

using System;
using AI_Vädering_APIML.Model;

namespace AI_Vädering_APIML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Kommun = @"Åtvidabergs kommun",
                BoArea = @"196",
                Rum = 6F,
                TomtArea = 795F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Pris with predicted Pris from sample data...\n\n");
            Console.WriteLine($"Kommun: {sampleData.Kommun}");
            Console.WriteLine($"BoArea: {sampleData.BoArea}");
            Console.WriteLine($"Rum: {sampleData.Rum}");
            Console.WriteLine($"TomtArea: {sampleData.TomtArea}");
            Console.WriteLine($"\n\nPredicted Pris: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
